### ISSUE TITLE
support for ubuntu 20.04

### ISSUE THREAD

**Issue by thomann061** [okcashpro/okcash#18]
Running the Okcash_5003_linux64.zip [Ubuntu 18] on Ubuntu 20.04 gives this error:

./okcash: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

**Comment by oktoshi** [comment]
Support added for ubuntu (all versions), centos, fedora, red hat, etc via AppImage over the 5005 release. cheers
