### ISSUE TITLE
After the synchronisation I get segmentation fault when I open the wallet in Raspberry PI 4

### ISSUE THREAD

**Issue by dancespiele** [okcashpro/okcash#21]
After the synchronisation when I try to open the wallet I get this famous `cpp` error:

```
qt5ct: D-Bus system tray: no
qt5ct: D-Bus global menu: no
[1]    25145 segmentation fault  ./okcash
```

I tried several times but the same issue always

**Comment by oktoshi** [comment]
We are working in the new ROKOS release and we will have look at this issue,
meanwhile you can compile the daemon "okcashd" and use it on the system while we recreate/debug the issue you are experiencing with the GUI. thanks for your report.

**Comment by oktoshi** [comment]
pushed a fix, please try 6.9.0.4 and let us know how it goes ;)

**Comment by oktoshi** [comment]
OK, give it a try to the new v6.9.0.4 ;) Let us know how it goes.

**Comment by dancespiele** [comment]
@oktoshi when I compile the new version 6.9.0.4 I get this error

```
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: nota:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
src/qt/clientmodel.cpp:246:89: error: ‘_2’ no se declaró en este ámbito
  246 |     uiInterface.NotifyAlertChanged.disconnect(boost::bind(NotifyAlertChanged, this, _1, _2));
      |                                                                                         ^~
```

it means that `_2` was not declared

**Comment by dancespiele** [comment]
I remove this argument but still having fail for argument that was not declared.

**Comment by oktoshi** [comment]
kk, let me grab the pi and check it out directly on it, will update you when done

**Comment by oktoshi** [comment]
give it a try again with new v 6905

**Comment by dancespiele** [comment]
I will try this evening and I will tell you

**Comment by dancespiele** [comment]
I still get the issue and I download a new repository in another Raspberry Pi. It also happens with the argument 2 and 3.
The OS that I use is Manjaro arm64

```
src/qt/transactiontablemodel.cpp: En la funciÃ³n miembro âvoid TransactionTableModel::subscribeToCoreSignals()â:
src/qt/transactiontablemodel.cpp:641:90: error: â_1â no se declarÃ³ en este Ã¡mbito
  641 |     wallet->NotifyTransactionChanged.connect(boost::bind(NotifyTransactionChanged, this, _1, _2, _3));
      |                                                                                          ^~
src/qt/transactiontablemodel.cpp:641:90: nota: alternativas sugeridas:
ÿ
```

**Comment by oktoshi** [comment]
gotcha, thanks for the feedback, segfault is fixed now for ubuntu 20 and new OS, we will take a dive on the manjaro and update in here when done, thanks

**Comment by dancespiele** [comment]
I have the same error if I compile in Manjaro x86_64 however the AppImage works

**Comment by oktoshi** [comment]
please check if the new patch works for manjaro raspberry also, it should but we had not the time to live test the pi.

Just pushed a patch for manjaro users to fix this:
steps:
1 clone https://github.com/okcashpro/okcash
2 go to:  cd okcash/oktools/manjaro5205
3 chmod -R +x *
4 sh ./1patch5205.sh
5 sh ./2manjarodeps.sh
6 select which build you wanna go for: sh (./installfull.sh or ./installnode.sh or ./installgui.sh)
Enjoy.

Feel free to close the issue after finding out it works, if no response we close in 24hrs.

**Comment by dancespiele** [comment]
@oktoshi now the compile complete successfully however when I try to run the GUI or daemon I get this error.

```
EXCEPTION: St13runtime_error       
init_blockindex(): error opening database environment Invalid argument: /home/spielrs/.okcash/txleveldb: does not exist (create_if_missing is false)       
okcash in Runaway exception
```

**Comment by oktoshi** [comment]
maybe is because the berkeley db, check if your new build is using the 4.8 or the < 5
then backup your folder and start the new client with empty folder . db5 reads db4 but not the other way around,
if this is the issue the solution would be to compile the wallet with db5 (so its compatible with your previous build)
please share me your feedback so we can continue to debug and get you set ;)

**Comment by dancespiele** [comment]
@oktoshi  I guess that it is built with 4.8, how can I compile with .db5
By the way I get the same error although I remove the `.okcash` folder (I did backup but I'm trying in another computer for testing)

**Comment by dancespiele** [comment]
@oktoshi I removed the sources, also the berkeley db installed before (it was 4.8 and I have 5 version) and I cloned the sources again but I didn't execute this script `sh ./2manjarodeps.sh` and I compiled and now works. Thanks a lot!
