### ISSUE TITLE
OKCash v6.9 GUI wallet falsely appears empty

### ISSUE THREAD

**Issue by nar36104** [okcashpro/okcash#23]
(See also Jan 2021 Discord #help-by-users posts by geophokus)

Downloaded Okcash_Core-6903-linux86_64.AppImage
Made executable with Dolphin checkbox
Launched/Integrated with AppImageLauncher (dbl click the AppImage file)
Opened OKCash v6.9 using existing v5 wallet.dat
Reindex automatically completed in 4.5 hours

Reopened client and no coins, addresses, transaction history exist. GUI appears empty
Coin Control and listaddressgroupings show correct balances
Launch with -rescan does not fix problem

Also tried following DreamHunter steps on #help-by-users Discord channel:
Step 1: close wallet, and rename wallet.dat to walletorig.dat
Step 2: start the wallet so you get a new wallet.dat, create a new okcash address and copy it to notes
Step 3: close the ok wallet, rename the new wallet.dat to walletnew.dat , and rename walletorig.dat back to wallet.dat
Step 4: start the ok wallet, go to send page, click coin control, select inputs, and here select the addresses with the coins and click ok
Step 5: send all this coins to the new created address, after done, close wallet.
Step 6: rename wallet.dat to walletorig.dat and rename walletnew.dat to wallet.dat
Step 7: start your okcash wallet as usual (without the rescan or anything) else close and use the rescan.

This did not solve the problem but coins and transaction history did temporarily show up in GUI on steps 4 and 7. After restarting the client they disappeared again.

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Processors: 8 x AMD Ryzen Embedded V1605B with Radeon Vega Gfx
Memory: 30.3 GiB of RAM
Graphics Processor: AMD Ryzen Embedded V1605B with Radeon Vega Gf

![Empty_OKCash_Desktop](https://user-images.githubusercontent.com/70346030/105093813-8b939f80-5a60-11eb-8037-9985890d74ee.png)

**Comment by nar36104** [comment]
A workaround proposed by gnuzum on Discord channel help-by-users is working for now.

I simply extract the Appimage

./Okcash_Core-6903-linux86_64.AppImage --appimage-extract 

and run the executable directly

./squashfs-root/usr/bin/okcash

The GUI does not populate correctly every time but does work most of the time. Simply close/reopen the client to populate the GUI.

This also fixes another issue where the Settings -> OKClient Options windows are unpopulated until "Cancel" is clicked. Now Options are visible immediately when OKClient Options is opened.

**Comment by oktoshi** [comment]
please try compiling your OK wallet from source, if not able we will post a tutorial or release a manjaro compiled client to help solve your issue, AppImages are compiled over ubuntu 14 for max compatibility, but as linux distros are different, sometimes issues like this arise, we will check on it further.

**Comment by nar36104** [comment]
successfully built/run okcashd following buildok-node.sh instructions

no success building okcash GUI. Exit with errors. Tried make in CLI and also QT Creator on okcash.pro file

I do not have all of the details here but in one case I needed to add 
#include <QPainterPath>" to a .cpp file header
Also received many 
error: ‘_1’ was not declared in this scope
Tried solving by:
#include <functional> 
and change placeholders from "_1" to "std::placeholders::_1"

I'm not a developer though so I'm already far beyond my understanding and know-how. (Like this is my first time using QT Creator. I don't know what I'm doing and may mess something up.)

**Comment by oktoshi** [comment]
so far this issue seems to be exclusively related with the manjaro distro, we will work on it and we will post the fix,patch,tut as required, thanks for your feedback and patience on this issue.

**Comment by nar36104** [comment]
Ok thank you. Will update if I find success. I still have access to keys and coins and daemon works fine.

**Comment by oktoshi** [comment]
Just pushed a patch for manjaro users to fix this:
steps:
1 clone https://github.com/okcashpro/okcash
2 go to:  cd okcash/oktools/manjaro5205
3 chmod -R +x *
4 sh ./1patch5205.sh
5 sh ./2manjarodeps.sh
6 select which build you wanna go for: sh (./installfull.sh or ./installnode.sh or ./installgui.sh)
Enjoy.

Feel free to close the issue after finding out it works, if no response we close in 24hrs.

**Comment by nar36104** [comment]
Worked perfectly for my Manjaro system. Instant synced the blockchain and up and running OkCash GUI full node. Wallet is fully populated with transactions and balances.

Thanks toshi and other devs!! I am very pleased and grateful.
