### ISSUE TITLE
No possible to move amounts between accounts using the command move

### ISSUE THREAD

**Issue by dancespiele** [okcashpro/okcash#24]
I have a weird issue trying to move amounts between accounts in the daemon:
1. When I execute the command `move` it does without error
2. I can see the `move` operation when I execute the command `listtransactions`
```json
{
        "account" : "two",
        "category" : "move",
        "time" : 1610905538,
        "amount" : -4.00000000,
        "otheraccount" : "one",
        "comment" : ""
    },
    {
        "account" : "one",
        "category" : "move",
        "time" : 1610905538,
        "amount" : 4.00000000,
        "otheraccount" : "two",
        "comment" : ""
    }
}
```
3. After I change back the config to `staking only` and check with the command `getstakinginfo` that it is enabled and true I don't get any rewards since more than 4 days when before I was getting everyday

**Comment by oktoshi** [comment]
The network % of users staking is rising, probably you just need to wait until your stakes gets accepted by the network, dont worry tho, when your stake gets accepted it includes the weight it has accumulated, so you will get it in proportion of the waiting "staking" time.

Please check in the coming days and close the issue if you start to get them, else just post again so we can investigate further.

**Comment by dancespiele** [comment]
Yes I started to get them however I still have the issue about move okcash between accounts maybe I should split the ticket

**Comment by oktoshi** [comment]
good, let me close this ticket then and please open the new one if still required,
The "account" system is getting deprecated tho, maybe wold be better to manage the accounts directly with a layer and move/create addresses /(accounts) as required. feel free to reopen or make the new issue for tracking.
