### ISSUE TITLE
Cannot import wallet data from Coinomi 

### ISSUE THREAD

**Issue by viachy** [okcashpro/okcash#25]
Hello,

I have sent OKCash coins from an exchange to Coinomi wallet, not realizing that OKCash is no longer supported there.
I downloaded the OKCash v6.9.0.0-g wallet and have synced the blockchain. 
I have tried 10 or more times to import the coins using the 24 word mnemonic phrase and always receive "Congratulations..." message after I click on "Next step"  
Then, as advised by Reddit users [here ](https://www.reddit.com/r/OKcash/comments/l34d81/how_to_get_a_correct_private_key_from_coinomi/)
I go to console and enter the command "scanforalltxns 0" 
However my balance remains 0.00 OKCash.

Any help will be appreciated.

Thanks

**Comment by oktoshi** [comment]
if you got the "congratulations" then your mnemonic is already imported to your wallet, if you use coin control you will be able to see them, or do: getbalance      over your OK console.

To help with your issue on why is not showing it, please use the latest Okcash wallet, and share us your Operating System, thanks.

**Comment by viachy** [comment]
I am using the latest OK Cash HD wallet v6.9.0.0-g , on Windows 10 64-bit system. 
Just tried the getbalance command and the result is 0.0000 .. Also tried again scanforalltxns 0 followed by getbalance. Same result.

[This ](https://chainz.cryptoid.info/ok/address.dws?PDJryYfHDRZ1J8VUwvGBFT7FxvLU97wBXs.htm)is the transaction that I am trying to import with my mnemonic .. I see that next to Wallet it says None... so either I`m doing something wrong, or I need to enter also my private key somewhere. And it has not asked me to enter it anywhere..

**Comment by oktoshi** [comment]
please use the windows easy installer and install the latest wallet which is 6.9.0.3 and give it another try
also, when you import your mnemonic you do uncheck the bip 44 checkbox right?

**Comment by viachy** [comment]
Okay here is what I tried, 
1 . Uninstalled the HD wallet v6.9.0.0-g 
2. Downloaded the Windows easy installer and installed OK Wallet v6.9.0.3
3. I did not have to import the network, as probably the files have remained on my hard drive so the network was synced.
4. Went to Import wallet , entered my mnemonic phrase, unchecked the bip 44 checkbox, also entered my password for Coinomi wallet (although I`m not sure if it is needed or not).
5. After that the balance remained 0.000 
6. Went to console and tried the commands scanforalltxns 0 and getbalance.
7. Restarted the OK wallet
8. Balance is still 0.000 

:(

**Comment by oktoshi** [comment]
OK, please try an import again, without your coinomi password, the password is only required if your mnemonic was protected with a password, coinomi password for tx is a different one, so that might be the issue, please try and share me your feedback, but dont worry, we will get your coins, nobody has lost coins with OK and we are proud to keep that track, so we will get this sorted out.

**Comment by viachy** [comment]
I already did (without the password) and after that I entered the command scanforalltxns  but this time not with 0, but with 100000, and for the past 10-15 minutes it has been scanning transactions, which gives me hope that this time it might work. I`ll leave it overnight and will check what happened tomorrow, and I`ll come to provide update. 

I`ve been holding these coins for 2 or 3 years so I have patience :)

**Comment by oktoshi** [comment]
awesome! let us know how it goes

**Comment by viachy** [comment]
unfortunately balance still shows 0.000 :(

any other steps that I might take?

**Comment by oktoshi** [comment]
just to make sure you have your new account selected as main/default and it is activated at: OK Tools > Advanced HD config

**Comment by viachy** [comment]
when I go to Advanced HD config I see about 20 wallets that have been created while I`m attempting to recover the coins.
The last created wallet is set to default.  

  all of these wallets that have been created have a green / active status but the coins have not been recovered in any of them....

I am not sure anymore what can I do to recover them.

**Comment by oktoshi** [comment]
Please let us have a look directly to your wallet.dat so we can debug your issue, it seems it is just the need to properly activate the account with the coins in it.
Send me your wallet.dat file to: devteam@okcash.co   we will work on it and send it back properly activated and with your coins ready, will be easier to check and debug. on the mail title use: Viachy - wallet.dat - account fix
Thanks.

**Comment by viachy** [comment]
sent, as requested.

**Comment by oktoshi** [comment]
Sent back fixed with your coins in it.
the issue was just to mark the bip44 checkbox.
We deleted all traces of your wallet.dat in our systems.
But for added security move your coins to a new wallet only you have access to.
Closing the issue after your answer, else we close in 24hrs, kind regards.

**Comment by viachy** [comment]
I confirm that everything is okay now.

Thank you for the patience and the support.

You can close the issue.
BR
viachy
