### ISSUE TITLE
How can I list all the address that I have in my wallet with the RPC

### ISSUE THREAD

**Issue by dancespiele** [okcashpro/okcash#26]
How can I list all the address that I have in my wallet with the RPC? because with `listaddressgroupings` always I get an empty array in two of my wallet however in another I get an array of accounts with indent array of theirs addresses and their balances.
I don't know why in some wallets get empty array and another not but I cannot call this in order to build [my client for Okspiel](https://github.com/dancespiele/okspiel/blob/master/src/ok_client/client.rs)
For now I have to call `getaddressesbyaccount default` from my application making the limitation that the user cannot see another accounts of their wallets.
Is there another way to list the accounts with the address without adding anything in the config file `okcash.conf`

**Comment by lichtteil** [comment]
Did you try `okcashd listreceivedbyaddress 0 true` ?

**Comment by dancespiele** [comment]
@lichtteil I didn't know this command, I think this is what I need, thanks a lot!
