### ISSUE TITLE
Always I get connection refused although I open the port 6969

### ISSUE THREAD

**Issue by dancespiele** [okcashpro/okcash#27]
I'm trying to connect to the rpc from another machine however always I get this error:

curl: (7) Failed to connect to 192.168.178.37 port 6969: Connection refused

I open the port 6969 from the machine where I run the daemon and even I add in the config the option `rpcallowip` (based in the rpc bitcoin config) but the same connection issue. Without be able to connect my rpc from another machine my [app](https://github.com/dancespiele/okspiel) will not make sense

**Comment by oktoshi** [comment]
add this lines to your config file

listen=1
server=1
daemon=1

**Comment by dancespiele** [comment]
I added and I restart the node but still I get the error connection refused

**Comment by oktoshi** [comment]
add also
whitelist=YourallowedIP

and make sure you are using this format for curl
curl --user RPCuser:RPCpassword --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:6969/ -w '%{http_code}\n'

**Comment by dancespiele** [comment]
it looks like I need to add both 
whitelist=[MY_IP_ALLOWED]
rpcallowip=[MY_IP_ALLOWED]

Thanks now I can connect. Other think that I suggested you @oktoshi by dm in discord is that we should have a channel for developers in Okcash discord server
