### ISSUE TITLE
to execute some commands I shouldn't need to add enableaccounts in the config file

### ISSUE THREAD

**Issue by dancespiele** [okcashpro/okcash#28]
commands like `listaccounts`, `getbalance [address]`, `listreceivedbyaccount`, `listreceivedbyaddress` when I execute them I get this error:

```
error: {"code":-1,"message":"Accounting API is deprecated and will be removed in future.\nIt can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.\nIf you still want to enable it, add to your config file enableaccounts=1\n"}
```
I don't understand what is the point of this error when theses commands are only for retrieve info, also enable the option `enableaccounts` in the config file has the issue that after the daemon doesn't allow to stake.

The issue of not able to use theses commands makes a lot of limitations in order to create applications for Okcash blockchain or use the daemon

**Comment by dancespiele** [comment]
If I add `enableaccounts` I get this error if I execute `listaccounts`
```
error: {"code":-1,"message":"If you want to use accounting API, staking must be disabled, add to your config file staking=0\n"}
```
because of this it is an issue

**Comment by oktoshi** [comment]
enableaccounts is required to enable them, 
the accounts system needs more tuning to be fully dependent.
