### ISSUE TITLE
OkCash Wallet - Slow Sync

### ISSUE THREAD

**Issue by rwong81** [okcashpro/okcash#3]
Downloaded the OKCash Wallet and syncing is very slow. About 10% of the blockchain is sync'd every 8 hours which means the transferred OKCash tokens are not appearing and cannot be used for staking for over 80 hours.

Is this normal and can it be fixed? I have downloaded multiple wallets of other tokens without this issue.

**Comment by okorator** [comment]
Hello,

Please check out the Instant Sync process using the BOOTSTRAP: https://github.com/okcashpro/ok-blockchain

This will cut your total time down huge!  Think under an hour on most computers, don't quote me there :)  Come chat on discord and ping me if you have any trouble. 

http://discord.io/cryptocurrency

- OKorator
