### ISSUE TITLE
v.7 Wallet (Not Responding)

### ISSUE THREAD

**Issue by Cool-Bobandy** [okcashpro/okcash#32]
**EDIT: I resolved the problem. v.7 has to be run in Administrator mode on Windows 10**

Just downloaded the new V.7 Wallet 64 bit for Windows / Stand Alone.
The screen is just stuck on (Not Responding). I cannot interact with the wallet.
Same thing happened on OK Cash v6.9.0.7, but that one would seize up Windows 10 eventually.
I'd have to reboot. OK Cash v6.9.0.5 works fine.

This is what it looks like on my computer.
![OK Wallet V 7](https://user-images.githubusercontent.com/118983117/203786391-940762ef-ab37-4a47-8918-3cef02baaf52.png)

Any ideas on how to fix it and use the V.7 wallet ?
I deleted my Roaming/OK Cash folder and re-downloaded the entire block data.

**Comment by Cool-Bobandy** [comment]
Works fine with v.6.9.0.5-g
![OKCash v6 9 5-g](https://user-images.githubusercontent.com/118983117/203789452-979620d8-e8cd-4851-8265-6476c5cadc93.png)

**Comment by oktoshi** [comment]
Thanks for sharing your feedback, closing as reported now solved.
