### ISSUE TITLE
Fake stars?

### ISSUE THREAD

**Issue by manugarri** [okcashpro/okcash#33]
https://dagster.io/blog/fake-stars

**Comment by oktoshi** [comment]
Hi, from the development side of this project, we do not care about stars, forks, or vanity numbers; we do focus on usability, ease of access, and downloads; even so, with OK being a community-driven project, we've seen community giveaways inviting the users to star the GitHub, but other than that, we do not track the starts hence our surprise and excitement to learn about this tool to track them down.
Thanks a lot for sharing this handy resource and info, I already starred it btw. cheers.
